### ISSUE TITLE
NOT WORKING EMPIRE 

### ISSUE THREAD

**Issue by FrozenStargames** [PowerShellEmpire/Empire#1373]
## Empire Version
 idk but i think newest version and dev branch

## OS Information (Linux flavor, Python version)
python version is 3.x i updated it this day

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

when i typing ./setup/install.sh its showing this

./setup/install.sh
Сущ:1 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease
Сущ:2 http://kali.volia.net/kali kali-rolling InRelease    
Чтение списков пакетов… Готово
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Уже установлен пакет build-essential самой новой версии (12.6).
Уже установлен пакет default-jdk самой новой версии (2:1.11-72).
Уже установлен пакет g++ самой новой версии (4:8.3.0-1).
Уже установлен пакет libssl-dev самой новой версии (1.1.1c-1).
Уже установлен пакет libssl1.1 самой новой версии (1.1.1c-1).
Уже установлен пакет libxml2-dev самой новой версии (2.9.4+dfsg1-7+b3).
Уже установлен пакет make самой новой версии (4.2.1-1.2).
Уже установлен пакет python-dev самой новой версии (2.7.16-1).
Уже установлен пакет python-m2crypto самой новой версии (0.31.0-4).
Уже установлен пакет python-pip самой новой версии (18.1-5).
Уже установлен пакет swig самой новой версии (3.0.12-2).
Уже установлен пакет zlib1g-dev самой новой версии (1:1.2.11.dfsg-1+b1).
Следующие пакеты устанавливались автоматически и больше не требуются:
  giskismet kali-desktop-common libboost-program-options1.67.0
  libboost-python1.62.0 libboost-serialization1.67.0 libboost-system1.62.0
  libboost-test1.67.0 libboost-thread1.62.0 libboost-timer1.67.0 libcgal13
  libcharls1 libcrypt2 libcrystalhd3 libdouble-conversion1 libfcgi-bin
  libfcgi0ldbl libgeos-3.7.1 libhttp-parser2.8 libicu-le-hb0 libicu60
  libigdgmm5 liblwgeom-2.5-0 liblwgeom-dev libmozjs-52-0 libpoppler80
  libpyside1.2 libpython3.6 libpython3.6-dev libpython3.6-minimal
  libpython3.6-stdlib libqca-qt5-2 libqca-qt5-2-plugins libqca2
  libqca2-plugins libqgis-analysis2.18.25 libqgis-analysis2.18.28
  libqgis-core2.18.25 libqgis-core2.18.28 libqgis-core3.4.10 libqgis-core3.4.9
  libqgis-customwidgets libqgis-gui2.18.25 libqgis-gui2.18.28
  libqgis-gui3.4.10 libqgis-gui3.4.9 libqgis-native3.4.10 libqgis-native3.4.9
  libqgis-networkanalysis2.18.25 libqgis-networkanalysis2.18.28
  libqgis-server2.18.25 libqgis-server2.18.28 libqgispython2.18.25
  libqgispython2.18.28 libqt5designercomponents5 libqt5keychain1
  libqt5quickwidgets5 libqt5serialport5 libqtwebkit4 libqwt-qt5-6 libqwt6abi1
  libradare2-3.1 libsfcgal1 libshiboken1.2v5 libspatialindex4v5
  libspatialindex5 libtexlua52 libwhisker2-perl
  linux-headers-4.19.0-kali3-amd64 linux-headers-4.19.0-kali3-common
  linux-image-4.19.0-kali3-amd64 python-cycler python-dicttoxml
  python-jsonrpclib python-kiwisolver python-matplotlib
  python-matplotlib2-data python-mockito python-nassl python-owslib
  python-pypdf2 python-pyproj python-pyside.qtcore python-pyside.qtgui
  python-pyside.qtnetwork python-pyside.qtwebkit python-pyspatialite
  python-qgis python-qgis-common python-qt4-sql python-shapely python-slowaes
  python-subprocess32 python-unicodecsv python-whoosh python-xlsxwriter
  python3-iso8601 python3.6 python3.6-dev python3.6-minimal qdoc-qt5
  qt4-designer qt5-assistant qttools5-dev-tools ruby-dm-serializer
  ruby-faraday ruby-geoip ruby-libv8 ruby-ref ruby-therubyracer suckless-tools
Для их удаления используйте «sudo apt autoremove».
Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 5 пакетов не обновлено.
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (1.22)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 2)) (2.18.4)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (41.0.1)
Requirement already satisfied: iptools in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 4)) (0.7.0)
Requirement already satisfied: pydispatcher in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 5)) (2.0.5)
Requirement already satisfied: flask in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (1.0.2)
Requirement already satisfied: macholib in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 7)) (1.11)
Requirement already satisfied: dropbox in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 8)) (9.4.0)
Requirement already satisfied: pyOpenSSL in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 9)) (17.2.0)
Requirement already satisfied: pyinstaller in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 10)) (3.5)
Requirement already satisfied: zlib_wrapper in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 11)) (0.1.3)
Requirement already satisfied: netifaces in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 12)) (0.10.9)
Requirement already satisfied: M2Crypto in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 13)) (0.35.2)
Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 14)) (2.10.1)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from -r requirements.txt (line 15)) (2.6.1)
Requirement already satisfied: pyminifier in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 16)) (2.1)
Requirement already satisfied: xlutils in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 17)) (2.0.0)
Requirement already satisfied: pycrypto in /usr/lib/python3/dist-packages (from -r requirements.txt (line 18)) (2.6.1)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 2)) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 2)) (2018.8.24)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: altgraph>=0.15 in /usr/local/lib/python3.7/dist-packages (from macholib->-r requirements.txt (line 7)) (0.16.1)
Requirement already satisfied: six>=1.3.0 in /usr/lib/python3/dist-packages (from dropbox->-r requirements.txt (line 8)) (1.12.0)
Requirement already satisfied: xlwt>=0.7.4 in /usr/local/lib/python3.7/dist-packages (from xlutils->-r requirements.txt (line 17)) (1.3.0)
Requirement already satisfied: xlrd>=0.7.2 in /usr/local/lib/python3.7/dist-packages (from xlutils->-r requirements.txt (line 17)) (1.2.0)
You are using pip version 18.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Уже установлен пакет apt-transport-https самой новой версии (1.8.3).
Уже установлен пакет curl самой новой версии (7.65.3-1).
Уже установлен пакет gnupg самой новой версии (2.2.17-3).
Следующие пакеты устанавливались автоматически и больше не требуются:
  giskismet kali-desktop-common libboost-program-options1.67.0
  libboost-python1.62.0 libboost-serialization1.67.0 libboost-system1.62.0
  libboost-test1.67.0 libboost-thread1.62.0 libboost-timer1.67.0 libcgal13
  libcharls1 libcrypt2 libcrystalhd3 libdouble-conversion1 libfcgi-bin
  libfcgi0ldbl libgeos-3.7.1 libhttp-parser2.8 libicu-le-hb0 libicu60
  libigdgmm5 liblwgeom-2.5-0 liblwgeom-dev libmozjs-52-0 libpoppler80
  libpyside1.2 libpython3.6 libpython3.6-dev libpython3.6-minimal
  libpython3.6-stdlib libqca-qt5-2 libqca-qt5-2-plugins libqca2
  libqca2-plugins libqgis-analysis2.18.25 libqgis-analysis2.18.28
  libqgis-core2.18.25 libqgis-core2.18.28 libqgis-core3.4.10 libqgis-core3.4.9
  libqgis-customwidgets libqgis-gui2.18.25 libqgis-gui2.18.28
  libqgis-gui3.4.10 libqgis-gui3.4.9 libqgis-native3.4.10 libqgis-native3.4.9
  libqgis-networkanalysis2.18.25 libqgis-networkanalysis2.18.28
  libqgis-server2.18.25 libqgis-server2.18.28 libqgispython2.18.25
  libqgispython2.18.28 libqt5designercomponents5 libqt5keychain1
  libqt5quickwidgets5 libqt5serialport5 libqtwebkit4 libqwt-qt5-6 libqwt6abi1
  libradare2-3.1 libsfcgal1 libshiboken1.2v5 libspatialindex4v5
  libspatialindex5 libtexlua52 libwhisker2-perl
  linux-headers-4.19.0-kali3-amd64 linux-headers-4.19.0-kali3-common
  linux-image-4.19.0-kali3-amd64 python-cycler python-dicttoxml
  python-jsonrpclib python-kiwisolver python-matplotlib
  python-matplotlib2-data python-mockito python-nassl python-owslib
  python-pypdf2 python-pyproj python-pyside.qtcore python-pyside.qtgui
  python-pyside.qtnetwork python-pyside.qtwebkit python-pyspatialite
  python-qgis python-qgis-common python-qt4-sql python-shapely python-slowaes
  python-subprocess32 python-unicodecsv python-whoosh python-xlsxwriter
  python3-iso8601 python3.6 python3.6-dev python3.6-minimal qdoc-qt5
  qt4-designer qt5-assistant qttools5-dev-tools ruby-dm-serializer
  ruby-faraday ruby-geoip ruby-libv8 ruby-ref ruby-therubyracer suckless-tools
Для их удаления используйте «apt autoremove».
Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 5 пакетов не обновлено.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0   4748      0 --:--:-- --:--:-- --:--:--  4748
OK
Сущ:1 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease
Сущ:2 http://kali.volia.net/kali kali-rolling InRelease
Чтение списков пакетов… Готово
--2019-08-17 12:04:09--  http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu57_57.1-6_amd64.deb
Распознаётся archive.ubuntu.com (archive.ubuntu.com)… 91.189.88.162, 91.189.88.31, 91.189.88.24, ...
Подключение к archive.ubuntu.com (archive.ubuntu.com)|91.189.88.162|:80... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 404 Not Found
2019-08-17 12:04:09 ОШИБКА 404: Not Found.

dpkg: ошибка: cannot access archive 'libicu57_57.1-6_amd64.deb': Нет такого файла или каталога
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Уже установлен пакет powershell самой новой версии (6.2.2-1.debian.9).
Следующие пакеты устанавливались автоматически и больше не требуются:
  giskismet kali-desktop-common libboost-program-options1.67.0
  libboost-python1.62.0 libboost-serialization1.67.0 libboost-system1.62.0
  libboost-test1.67.0 libboost-thread1.62.0 libboost-timer1.67.0 libcgal13
  libcharls1 libcrypt2 libcrystalhd3 libdouble-conversion1 libfcgi-bin
  libfcgi0ldbl libgeos-3.7.1 libhttp-parser2.8 libicu-le-hb0 libicu60
  libigdgmm5 liblwgeom-2.5-0 liblwgeom-dev libmozjs-52-0 libpoppler80
  libpyside1.2 libpython3.6 libpython3.6-dev libpython3.6-minimal
  libpython3.6-stdlib libqca-qt5-2 libqca-qt5-2-plugins libqca2
  libqca2-plugins libqgis-analysis2.18.25 libqgis-analysis2.18.28
  libqgis-core2.18.25 libqgis-core2.18.28 libqgis-core3.4.10 libqgis-core3.4.9
  libqgis-customwidgets libqgis-gui2.18.25 libqgis-gui2.18.28
  libqgis-gui3.4.10 libqgis-gui3.4.9 libqgis-native3.4.10 libqgis-native3.4.9
  libqgis-networkanalysis2.18.25 libqgis-networkanalysis2.18.28
  libqgis-server2.18.25 libqgis-server2.18.28 libqgispython2.18.25
  libqgispython2.18.28 libqt5designercomponents5 libqt5keychain1
  libqt5quickwidgets5 libqt5serialport5 libqtwebkit4 libqwt-qt5-6 libqwt6abi1
  libradare2-3.1 libsfcgal1 libshiboken1.2v5 libspatialindex4v5
  libspatialindex5 libtexlua52 libwhisker2-perl
  linux-headers-4.19.0-kali3-amd64 linux-headers-4.19.0-kali3-common
  linux-image-4.19.0-kali3-amd64 python-cycler python-dicttoxml
  python-jsonrpclib python-kiwisolver python-matplotlib
  python-matplotlib2-data python-mockito python-nassl python-owslib
  python-pypdf2 python-pyproj python-pyside.qtcore python-pyside.qtgui
  python-pyside.qtnetwork python-pyside.qtwebkit python-pyspatialite
  python-qgis python-qgis-common python-qt4-sql python-shapely python-slowaes
  python-subprocess32 python-unicodecsv python-whoosh python-xlsxwriter
  python3-iso8601 python3.6 python3.6-dev python3.6-minimal qdoc-qt5
  qt4-designer qt5-assistant qttools5-dev-tools ruby-dm-serializer
  ruby-faraday ruby-geoip ruby-libv8 ruby-ref ruby-therubyracer suckless-tools
Для их удаления используйте «apt autoremove».
Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 5 пакетов не обновлено.
ls: невозможно получить доступ к '/opt/microsoft/powershell/*/DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY': Нет такого файла или каталога
xar-1.6.1/
xar-1.6.1/ChangeLog
xar-1.6.1/INSTALL
xar-1.6.1/LICENSE
xar-1.6.1/Makefile.in
xar-1.6.1/NEWS
xar-1.6.1/autogen.sh
xar-1.6.1/cfghdrs.stamp.in
xar-1.6.1/cfgoutputs.stamp.in
xar-1.6.1/config.guess
xar-1.6.1/config.sub
xar-1.6.1/configure.ac
xar-1.6.1/include/
xar-1.6.1/include/config.h.in
xar-1.6.1/include/xar.h.in
xar-1.6.1/install-sh
xar-1.6.1/lib/
xar-1.6.1/lib/Makefile.inc.in
xar-1.6.1/lib/appledouble.h
xar-1.6.1/lib/archive.c
xar-1.6.1/lib/archive.h
xar-1.6.1/lib/arcmod.c
xar-1.6.1/lib/arcmod.h
xar-1.6.1/lib/asprintf.h
xar-1.6.1/lib/b64.c
xar-1.6.1/lib/b64.h
xar-1.6.1/lib/bzxar.c
xar-1.6.1/lib/bzxar.h
xar-1.6.1/lib/darwinattr.c
xar-1.6.1/lib/darwinattr.h
xar-1.6.1/lib/data.c
xar-1.6.1/lib/data.h
xar-1.6.1/lib/ea.c
xar-1.6.1/lib/ea.h
xar-1.6.1/lib/err.c
xar-1.6.1/lib/ext2.c
xar-1.6.1/lib/ext2.h
xar-1.6.1/lib/fbsdattr.c
xar-1.6.1/lib/fbsdattr.h
xar-1.6.1/lib/filetree.c
xar-1.6.1/lib/filetree.h
xar-1.6.1/lib/hash.c
xar-1.6.1/lib/hash.h
xar-1.6.1/lib/io.c
xar-1.6.1/lib/io.h
xar-1.6.1/lib/libxar.la.in.in
xar-1.6.1/lib/linuxattr.c
xar-1.6.1/lib/linuxattr.h
xar-1.6.1/lib/lzmaxar.c
xar-1.6.1/lib/lzmaxar.h
xar-1.6.1/lib/macho.c
xar-1.6.1/lib/macho.h
xar-1.6.1/lib/script.c
xar-1.6.1/lib/script.h
xar-1.6.1/lib/signature.c
xar-1.6.1/lib/signature.h
xar-1.6.1/lib/stat.c
xar-1.6.1/lib/stat.h
xar-1.6.1/lib/strmode.h
xar-1.6.1/lib/subdoc.c
xar-1.6.1/lib/subdoc.h
xar-1.6.1/lib/util.c
xar-1.6.1/lib/util.h
xar-1.6.1/lib/zxar.c
xar-1.6.1/lib/zxar.h
xar-1.6.1/src/
xar-1.6.1/src/Makefile.inc.in
xar-1.6.1/src/xar.1
xar-1.6.1/src/xar.c
xar-1.6.1/test/
xar-1.6.1/test/attr
xar-1.6.1/test/buffer.c
xar-1.6.1/test/checksums
xar-1.6.1/test/compression
xar-1.6.1/test/data
xar-1.6.1/test/data.xsl
xar-1.6.1/test/functions
xar-1.6.1/test/hardlink
xar-1.6.1/test/heap
xar-1.6.1/test/heap1.xsl
xar-1.6.1/test/validate.c
xar-1.6.1/xar.spec.in
xar-1.6.1/xar_README.txt
xar-1.6.1/autom4te.cache/
xar-1.6.1/autom4te.cache/requests
xar-1.6.1/autom4te.cache/traces.0
xar-1.6.1/autom4te.cache/output.0
xar-1.6.1/configure
xar-1.6.1/config.log
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for ld... /usr/bin/ld
checking for ar... /usr/bin/ar
checking for ranlib... /usr/bin/ranlib
checking for autoconf... no
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdint.h... (cached) yes
checking ext2fs/ext2_fs.h usability... no
checking ext2fs/ext2_fs.h presence... no
checking for ext2fs/ext2_fs.h... no
checking sys/statfs.h usability... yes
checking sys/statfs.h presence... yes
checking for sys/statfs.h... yes
checking sys/xattr.h usability... yes
checking sys/xattr.h presence... yes
checking for sys/xattr.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/extattr.h usability... no
checking sys/extattr.h presence... no
checking for sys/extattr.h... no
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking for lgetxattr... yes
checking for lsetxattr... yes
checking for getxattr... yes
checking for setxattr... yes
checking for getattrlist... no
checking for setattrlist... no
checking for lchmod... no
checking for lchown... yes
checking for chflags... no
checking for statvfs... yes
checking for statfs... yes
checking for strmode... no
checking for struct statfs.f_fstypename... no
checking for struct statvfs.f_fstypename... no
checking for struct stat.st_flags... no
checking size of uid_t... 4
checking size of gid_t... 4
checking size of ino_t... 8
checking size of dev_t... 8
checking for acl_get_file in -lacl... no
checking for asprintf... yes
checking for xml2-config... /usr/bin/xml2-config
checking for libxml >= 2.6.11... 2.9.4
checking libxml/xmlwriter.h usability... yes
checking libxml/xmlwriter.h presence... yes
checking for libxml/xmlwriter.h... yes
checking openssl/evp.h usability... yes
checking openssl/evp.h presence... yes
checking for openssl/evp.h... yes
checking for OPENSSL_init_crypto in -lcrypto... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for deflate in -lz... yes
checking bzlib.h usability... no
checking bzlib.h presence... no
checking for bzlib.h... no
checking for BZ2_bzCompress in -lbz2... no
checking lzma.h usability... no
checking lzma.h presence... no
checking for lzma.h... no
checking for lzma_code in -llzma... no
configure: creating ./config.status
config.status: creating cfgoutputs.stamp
config.status: creating Makefile
config.status: creating include/xar.h
config.status: creating lib/Makefile.inc
config.status: creating lib/libxar.la.in
config.status: creating src/Makefile.inc
config.status: creating xar.spec
config.status: creating cfghdrs.stamp
config.status: cfghdrs.stamp is unchanged
config.status: creating include/config.h
config.status: include/config.h is unchanged
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/archive.c -o lib/archive.o
lib/archive.c: In function ‘xar_close’:
lib/archive.c:469:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
  int ret, retval = 0;
      ^~~
lib/archive.c: In function ‘xar_unserialize’:
lib/archive.c:1684:12: warning: variable ‘noattr’ set but not used [-Wunused-but-set-variable]
  int type, noattr, ret;
            ^~~~~~
lib/archive.c:1683:33: warning: variable ‘uri’ set but not used [-Wunused-but-set-variable]
  const xmlChar *name, *prefix, *uri;
                                 ^~~
lib/archive.c:1683:24: warning: variable ‘prefix’ set but not used [-Wunused-but-set-variable]
  const xmlChar *name, *prefix, *uri;
                        ^~~~~~
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/arcmod.c -o lib/arcmod.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/bzxar.c -o lib/bzxar.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/darwinattr.c -o lib/darwinattr.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/data.c -o lib/data.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/ea.c -o lib/ea.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/err.c -o lib/err.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/ext2.c -o lib/ext2.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/fbsdattr.c -o lib/fbsdattr.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/filetree.c -o lib/filetree.o
lib/filetree.c: In function ‘xar_prop_next’:
lib/filetree.c:353:7: warning: variable ‘err’ set but not used [-Wunused-but-set-variable]
   int err;
       ^~~
lib/filetree.c:395:7: warning: variable ‘err’ set but not used [-Wunused-but-set-variable]
   int err;
       ^~~
lib/filetree.c: In function ‘xar_file_next’:
lib/filetree.c:850:8: warning: variable ‘err’ set but not used [-Wunused-but-set-variable]
    int err;
        ^~~
lib/filetree.c: In function ‘xar_prop_unserialize’:
lib/filetree.c:1058:10: warning: variable ‘err’ set but not used [-Wunused-but-set-variable]
      int err;
          ^~~
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/io.c -o lib/io.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/lzmaxar.c -o lib/lzmaxar.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/linuxattr.c -o lib/linuxattr.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/hash.c -o lib/hash.o
lib/hash.c: In function ‘xar_format_hash’:
lib/hash.c:238:3: warning: ‘strncat’ output may be truncated copying 2 bytes from a string of length 2 [-Wstringop-truncation]
   strncat(result,hexValue,2);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/signature.c -o lib/signature.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/stat.c -o lib/stat.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/subdoc.c -o lib/subdoc.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/util.c -o lib/util.o
lib/util.c: In function ‘xar_get_path’:
lib/util.c:97:7: warning: variable ‘err’ set but not used [-Wunused-but-set-variable]
   int err;
       ^~~
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/zxar.c -o lib/zxar.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/script.c -o lib/script.o
gcc -Wall -g -O2  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/macho.c -o lib/macho.o
gcc -shared -Wl,-soname,libxar.so.1 -o lib/librxar.so.1 lib/archive.o lib/arcmod.o lib/b64.o lib/bzxar.o lib/darwinattr.o lib/data.o lib/ea.o lib/err.o lib/ext2.o lib/fbsdattr.o lib/filetree.o lib/io.o lib/lzmaxar.o lib/linuxattr.o lib/hash.o lib/signature.o lib/stat.o lib/subdoc.o lib/util.o lib/zxar.o lib/script.o lib/macho.o -Llib  -lz -lcrypto  -lxml2
rm -f lib/librxar.so
ln -s librxar.so.1 lib/librxar.so
gcc -shared -Wl,-soname,libxar.so.1 -o lib/libxar.so.1 lib/archive.o lib/arcmod.o lib/b64.o lib/bzxar.o lib/darwinattr.o lib/data.o lib/ea.o lib/err.o lib/ext2.o lib/fbsdattr.o lib/filetree.o lib/io.o lib/lzmaxar.o lib/linuxattr.o lib/hash.o lib/signature.o lib/stat.o lib/subdoc.o lib/util.o lib/zxar.o lib/script.o lib/macho.o -Llib  -lz -lcrypto  -lxml2
rm -f lib/libxar.so
ln -s libxar.so.1 lib/libxar.so
sed -e s/@LIBXAR_SNAME@/libxar.so.1/ -e s/@LIBXAR_LNAME@/libxar.so/ -e s/@LIBXAR_ANAME@/libxar.a/ < lib/libxar.la.in > lib/libxar.la
gcc -Wall -g -O2  -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c src/xar.c -o src/xar.o
src/xar.c: In function ‘is_valid_dir’:
src/xar.c:672:6: warning: variable ‘err’ set but not used [-Wunused-but-set-variable]
  int err, result, curdir = open(".", O_RDONLY);
      ^~~
src/xar.c: In function ‘archive’:
src/xar.c:1212:7: warning: variable ‘err’ set but not used [-Wunused-but-set-variable]
   int err;
       ^~~
src/xar.c: In function ‘main’:
src/xar.c:1932:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
  int ret;
      ^~~
src/xar.c: In function ‘signingCallback’:
src/xar.c:974:2: warning: ‘strncpy’ output truncated before terminating nul copying 10 bytes from a string of the same length [-Wstringop-truncation]
  strncpy((char *)*signed_data, "helloworld", 10); /* debug */
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/xar.c: In function ‘replace_sign’:
src/xar.c:778:2: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  strncpy(new_xar_path, temp_dir, new_xar_path_len);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/xar.c:772:21: note: length computed here
  new_xar_path_len = strlen(temp_dir) + 12;
                     ^~~~~~~~~~~~~~~~
gcc -Wall -g -O2  -o src/xar src/xar.o -Wl,-rpath,/root/Empire/setup/xar-1.6.1/lib -Llib  lib/libxar.a -lz -lcrypto  -lxml2
gcc -Wall -g -O2  -o src/ixar src/xar.o -Wl,-rpath,/usr/local/lib -Llib  lib/libxar.so.1 -lz -lcrypto  -lxml2
/usr/bin/install -c -d /usr/local/include/xar
/usr/bin/install -c -m 0644  include/xar.h /usr/local/include/xar
/usr/bin/install -c -d /usr/local/lib
/usr/bin/install -c -m 0755 lib/libxar.so.1 /usr/local/lib
rm -f /usr/local/lib/libxar.so
ln -s libxar.so.1 /usr/local/lib/libxar.so
/usr/bin/install -c -m 0644 lib/libxar.a /usr/local/lib
/usr/bin/install -c -m 0644 lib/libxar.la /usr/local/lib
/usr/bin/install -c -d /usr/local/bin
/usr/bin/install -c -m 0755 src/ixar /usr/local/bin/xar
/usr/bin/install -c -d /usr/local/share/man/man1
/usr/bin/install -c -m 0644 src/xar.1 /usr/local/share/man/man1
fatal: целевой путь «bomutils» уже существует и не является пустым каталогом.
make: Цель «all» не требует выполнения команд.
install -d /usr/bin
install -d /usr/share/man/man1
install -m 0755 build/bin/mkbom build/bin/dumpbom build/bin/lsbom build/bin/ls4mkbom /usr/bin
install -m 0644 build/man/mkbom.1.gz build/man/dumpbom.1.gz build/man/lsbom.1.gz build/man/ls4mkbom.1.gz /usr/share/man/man1
install -d /usr/bin
install -d /usr/share/man/man1
install -m 0755 build/bin/mkbom build/bin/dumpbom build/bin/lsbom build/bin/ls4mkbom /usr/bin
install -m 0644 build/man/mkbom.1.gz build/man/dumpbom.1.gz build/man/lsbom.1.gz build/man/ls4mkbom.1.gz /usr/share/man/man1

 [>] Enter server negotiation password, enter for random generation: 
Traceback (most recent call last):
  File "./setup_database.py", line 120, in <module>
    )''')
sqlite3.OperationalError: table "agents" already exists

 [*] Certificate written to ../data/empire-chain.pem
 [*] Private key written to ../data/empire-priv.key

 [*] Setup complete!

root@kali:~/Empire# ./empire
Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Empire/lib/common/__init__.py", line 8, in <module>
    import helpers
  File "/root/Empire/lib/common/helpers.py", line 50, in <module>
    import iptools
ImportError: No module named iptools

**Comment by gabyavra** [comment]
same here

**Comment by gburkle** [comment]
I was getting the same issue, and I was able to make it run after manually installing all the modules specific for python3. 
So one by one (I'm running Kali)-> apt-get install python3-iptools 
Run it again, and install the next missing module. 
Then run ./setup/reset.sh and install those python3-modules as well.
I think the installer is checking for the python2 modules instead of the python3 or something.
