### ISSUE TITLE
Empire run error: No module named iptools

### ISSUE THREAD

**Issue by pawp81** [PowerShellEmpire/Empire#1380]
## Empire Version
3.0

## OS Information (Linux flavor, Python version)
Kali Linux
Python 3.7.5 & 2.7.17

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Successfully launching Empire by running ./empire

## Screenshot of error, embedded text output, or Pastebin link to the error
./empire Traceback (most recent call last): 
File "./empire", line 14, in <module> 
from lib.common import empire, helpers 
File "/opt/Empire/lib/common/__init__.py", line 10, in <module> 
import helpers File "/opt/Empire/lib/common/helpers.py", line 58, in <module> 
import iptools 
ModuleNotFoundError: No module named 'iptools'

## Any additional information
All requirements seem to be satisfied: https://pastebin.com/hi6MtGnj

**Comment by MthwBrwn** [comment]
The error I was initially seeing was exactly the same as yours. 

I was able to make it work by specifying which python I wanted to use pip on (python -m pip install)
Recent changes to pip have made this necessary.

Each time I ran ./empire I got a new module error and then installed one be one until I got a NoneType error and then switched to running ./setup/reset.sh . I continued this way until Empire start running properly. 

All in all, here are the commands I had to run in order to load the dependencies. 

python -m pip install iptools

python -m pip install netifaces

python -m pip install pydispatch

python -m pip install pydispatcher

python -m pip install zlib_wrapper

python -m pip install macholib

python -m pip install xlrd

python -m pip install xlutils

python -m pip install pyminifier

python -m pip install dropbox


Let me know if you get yours to work. 

Mt.

**Comment by pawp81** [comment]
I moved forward by installing pip for python3.7
apt install python3-pip
pything3.7 -m pip install pip
And then the pre-requisites:
python3.7 -m pip install iptools
python3.7 -m pip install netifaces
etc

**Comment by pawp81** [comment]
Now I am getting the following error:
root@kali:/opt/Empire# ./empire
Traceback (most recent call last):
  File "./empire", line 1424, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 97, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: cannot unpack non-iterable NoneType object

**Comment by MthwBrwn** [comment]
right, same deal when I did mine--Thats the Nonetype error- now you'll need to load the dependencies for the DB - 

**run ./setup/reset.sh**  and load the dependencies like you have been doing.

**Comment by Hubbl3** [comment]
@pawp81 @MthwBrwn This is the original Empire project repo. We are supporting the fork here:

https://github.com/BC-SECURITY/Empire

we released a bug fix update last week that addresses this issue if you reclone the project

**Comment by MthwBrwn** [comment]
Thanks - I'll take a look.

**Comment by gladiatorgiftson** [comment]
pip install --upgrade -r requirements.txt this will do the trick
