### ISSUE TITLE
Traceback after payload is executed.

### ISSUE THREAD

**Issue by leebaird** [PowerShellEmpire/Empire#172]
## Empire Version
latest, 4-2-16

## OS Information (Linux flavor, Python version)
Kali rolling

root@kali:~# uname -a
Linux kali 4.4.0-kali1-amd64 #1 SMP Debian 4.4.6-1kali1 (2016-03-18) x86_64 GNU/Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Empire: stager/launcher_bat) > execute

[*] Stager output written out to: /root/Desktop/launcher.bat

I copy the .bat file over to my Windows 7 VM and execute it.
==============================================================

(Empire: stager/launcher_bat) > [+] Initial agent F34FZE2ZZ2TC1NPB from 10.1.8.9 now active
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49313)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49314)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49315)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49316)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49317)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49318)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49319)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49320)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49321)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49322)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49323)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49324)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49325)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49326)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49327)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49328)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49329)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('10.1.8.9', 49330)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/opt/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/opt/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/opt/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings
----------------------------------------
<ctrl+c>

[>] Exit? [y/N] -y

**Comment by enigma0x3** [comment]
This is because 1.5 updated some stuff in the backend db. I recommend running ./reset.sh. Let me know if this doesn't fix it for you.

Thanks!
