### ISSUE TITLE
Error on usestager/launcher_bat

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#188]
## Empire Version
Latest, i removed Empire directory, and did git clone

## OS Information (Linux flavor, Python version)
Kali

Issue:
Error on connection when using launcher_bat

If i use just `(Empire: listeners) > launcher 2`  then copy and paste the output on my target machine, then i get an agent and no issues

But when using usestager/launcher_bat, as soon as i run the bat file on target machine it gives the following error on my Empire
```

Exception happened during processing of request from ('1xx.xx.xx.xx[myip]', 42016)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/root/Empire/lib/common/http.py", line 80, in do_GET
    name, sessionID = part.split("=")
ValueError: too many values to unpack


```

the above continuously repeats 

My settings for launcher bat

```
`(Empire: stager/launcher_bat) > info

Name: BAT Launcher

Description:
  Generates a self-deleting .bat launcher for
  Empire.

Options:

  Name             Required    Value             Description
  ----             --------    -------           -----------
  ProxyCreds       False       default           Proxy credentials
                                                 ([domain\]username:password) to use for
                                                 request (default, none, or other).
  StagerRetries    False       5                 Times for the stager to retry
                                                 connecting.
  Listener         True        test2             Listener to generate stager for.
  OutFile          False       /tmp/new.bat File to output .bat launcher to,
                                                 otherwise displayed on the screen.
  Proxy            False       default           Proxy to use for request (default, none,
                                                 or other).
  UserAgent        False       default           User-agent string to use for the staging
                                                 request (default, none, or other).
  Delete           False       True              Switch. Delete .bat after running.

`
```

**Comment by HarmJ0y** [comment]
This appears to be an issue with the staging process. Can you run **./empire --debug**, retry the launcher, and then sanitize/post the relevant sections of the **empire.debug** debug file?

**Comment by HarmJ0y** [comment]
If there's no response within the next week we'll close out this issue.
