### ISSUE TITLE
A random Error

### ISSUE THREAD

**Issue by honeyfairy** [PowerShellEmpire/Empire#209]
## Empire Version
Latest Dev

## OS Information (Linux flavor, Python version)
Kali 64

The following error sometimes pops up while using Empire Powershell, although I dont see any issues before or after this message appears. Could this be safely ignored? 
## Screenshot of error, embedded text output, or Pastebin link to the error
```
Exception happened during processing of request from ('192.x.x.x', 54858)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
----------------------------------------

```

(The 192.x.x.x ip is my WAN IP, I have an agent connected from this IP, and I am logged on to my server via SSH)

**Comment by HarmJ0y** [comment]
Not sure why that happens exactly, but it's an issue with the base HTTP server components. You can quickly restart the server if wanted. Once we move to Flask for HTTP in the backend this should no longer be an issue.
