### ISSUE TITLE
in _handle_request_noblock : When agent attempts to connect

### ISSUE THREAD

**Issue by brandontict** [PowerShellEmpire/Empire#278]
## OS info 
Kali 2016.1  
4.6.0-kali1-amd64 #1 SMP Debian 4.6.2-2kali2 (2016-06-28) x86_64 GNU/Linux
Python 2.7.12
 Kali updated daily via apt-get update && apt-get dist-upgrade  

## Issue 
When I attempt to use macro stager, launcher_bat or launcher_vbs on my Windows 10 lab I get the same issue on each one.

UPDATE: I've also tried the launcher_vbs stager on my virtual installation of Windows Server 2012 R2 running on latest vmware, same outcome . 

``(Empire)` > [+] Initial agent AZADHT1VEDNGZZSG from 192.168.0.22 now active
[+] Initial agent 3R43K3ENFXFHRLKK from 192.168.0.22 now active
----------------------------------------
Exception happened during processing of request from ('192.168.0.22', 56492)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/pen/payload/Empire/lib/common/http.py", line 86, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/pen/payload/Empire/lib/common/agents.py", line 1133, in process_get
    taskings = self.get_agent_tasks(sessionID)
  File "/pen/payload/Empire/lib/common/agents.py", line 825, in get_agent_tasks
    cur.execute("SELECT taskings FROM agents WHERE session_id=?", [sessionID])
OperationalError: no such column: taskings``

Empire states 3 agents are active.When going to agent menu, I receive 
'[!] Exception: need more than 29 values to unpack' 

Ive included empire.debug  http://pastebin.com/4vuSgtb7

## Any additional information
Had no issues with empire prior to upgrading Kali to the latest 2016.1 version.
I had pulled most recent version of empire from Git and I have also ran  the installation script again 

Thanks in advance

**Comment by HarmJ0y** [comment]
The '[!] Exception: need more than 29 values to unpack' error sounds like some type of code is out of sync. Can you try cloning a fresh copy of Empire, running through a fresh setup, and retrying?

**Comment by enigma0x3** [comment]
Closing due to inactivity
